<?php

namespace Modules\Visitor\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class UpdateGuestRequest extends FormRequest
{
    public function rules(): array
    {

        return [
            'first_name' => ['required', 'string', 'regex:/(^[A-Za-z ]+$)+/'],
            'last_name' => ['required', 'string', 'regex:/(^[A-Za-z ]+$)+/'],
            'patronymic' => ['nullable', 'string', 'regex:/(^[A-Za-z ]+$)+/'],
            'company_name' => ['required', 'string'],
            'phone_number' => ['nullable', 'string'],
            'passport_number' => [Rule::requiredIf((bool)filter_var($this->is_vip, FILTER_VALIDATE_BOOLEAN)), 'unique:guests,passport_number,' . $this->guest->id],
            'is_vip' => ['boolean'],
            'photo' => ['nullable', 'image'],
        ];
    }

    public function authorize(): bool
    {
        return auth()->check();
    }

    protected function prepareForValidation()
    {
        $this->merge([
            'is_vip' => filter_var($this->get('is_vip'), FILTER_VALIDATE_BOOLEAN),
        ]);
    }

    public function messages()
    {
        return [
            'passport_number.unique' => 'Серия паспорта уже существует'
        ]; // TODO: Change the autogenerated stub
    }
}
